#Enable Roles and Features for XMPie and FFcore
#Tested on Server 2012r2
#Tested on Server 2016
#Tested on Server 2019

Install-WindowsFeature "FileAndStorage-Services"
Install-WindowsFeature "File-Services"
Install-WindowsFeature "FS-FileServer"
Install-WindowsFeature "Storage-Services"
Install-WindowsFeature "Print-Services"
Install-WindowsFeature "Print-Server"
Install-WindowsFeature "Web-Server"
Install-WindowsFeature "Web-WebServer"
Install-WindowsFeature "Web-Common-Http"
Install-WindowsFeature "Web-Default-Doc"
Install-WindowsFeature "Web-Dir-Browsing"
Install-WindowsFeature "Web-Http-Errors"
Install-WindowsFeature "Web-Static-Content"
Install-WindowsFeature "Web-Http-Redirect"
Install-WindowsFeature "Web-Health"
Install-WindowsFeature "Web-Http-Logging"
Install-WindowsFeature "Web-Custom-Logging"
Install-WindowsFeature "Web-Log-Libraries"
Install-WindowsFeature "Web-Request-Monitor"
Install-WindowsFeature "Web-Http-Tracing"
Install-WindowsFeature "Web-Performance"
Install-WindowsFeature "Web-Stat-Compression"
Install-WindowsFeature "Web-Security"
Install-WindowsFeature "Web-Filtering"
Install-WindowsFeature "Web-Basic-Auth"
Install-WindowsFeature "Web-Cert-Auth"
Install-WindowsFeature "Web-Windows-Auth"
Install-WindowsFeature "Web-App-Dev"
Install-WindowsFeature "Web-Net-Ext"
Install-WindowsFeature "Web-Net-Ext45"
Install-WindowsFeature "Web-ASP"
Install-WindowsFeature "Web-Asp-Net"
Install-WindowsFeature "Web-Asp-Net45"
Install-WindowsFeature "Web-ISAPI-Ext"
Install-WindowsFeature "Web-ISAPI-Filter"
Install-WindowsFeature "Web-Includes"
Install-WindowsFeature "Web-Ftp-Server"
Install-WindowsFeature "Web-Ftp-Service"
Install-WindowsFeature "Web-Ftp-Ext"
Install-WindowsFeature "Web-Mgmt-Tools"
Install-WindowsFeature "Web-Mgmt-Console"
Install-WindowsFeature "Web-Mgmt-Compat"
Install-WindowsFeature "Web-Metabase"
Install-WindowsFeature "Web-Lgcy-Mgmt-Console"
Install-WindowsFeature "Web-Lgcy-Scripting"
Install-WindowsFeature "Web-WMI"
Install-WindowsFeature "Web-Scripting-Tools"
Install-WindowsFeature "Web-Mgmt-Service"
Install-WindowsFeature "NET-Framework-Features"
Install-WindowsFeature "NET-Framework-Core"
Install-WindowsFeature "NET-HTTP-Activation"
Install-WindowsFeature "NET-Framework-45-Features"
Install-WindowsFeature "NET-Framework-45-Core"
Install-WindowsFeature "NET-Framework-45-ASPNET"
Install-WindowsFeature "NET-WCF-Services45"
Install-WindowsFeature "NET-WCF-HTTP-Activation45"
Install-WindowsFeature "NET-WCF-TCP-PortSharing45"
Install-WindowsFeature "InkAndHandwritingServices"
Install-WindowsFeature "Server-Media-Foundation"
Install-WindowsFeature "MSMQ"
Install-WindowsFeature "MSMQ-Services"
Install-WindowsFeature "MSMQ-Server"
Install-WindowsFeature "MSMQ-Directory"
Install-WindowsFeature "MSMQ-HTTP-Support"
Install-WindowsFeature "FS-SMB1"
Install-WindowsFeature "User-Interfaces-Infra"
Install-WindowsFeature "Server-Gui-Mgmt-Infra"
Install-WindowsFeature "Desktop-Experience"
Install-WindowsFeature "Server-Gui-Shell"
Install-WindowsFeature "PowerShellRoot"
Install-WindowsFeature "PowerShell"
Install-WindowsFeature "PowerShell-V2"
Install-WindowsFeature "PowerShell-ISE"
Install-WindowsFeature "WAS"
Install-WindowsFeature "WAS-Process-Model"
Install-WindowsFeature "WAS-NET-Environment"
Install-WindowsFeature "WAS-Config-APIs"
Install-WindowsFeature "WoW64-Support"

pause

Get-WindowsFeature


pause

Get-WindowsFeature | ? {$_.Installed -match "True"} | Select -exp Name
Get-WindowsFeature | ? {$_.Installed -match "True"}